### ISSUE TITLE
Rust: says we are missing listing key exercises but that is checked

### ISSUE THREAD

**Issue by efx** [exercism/v3-dashboard#27]
If you go to the Rust track status it says we still need to list out key concepts:
https://v3.exercism.io/rust/maintaining/launch

I would expect it to say we have finished that since we have itemized the bulk of them and our readme has it [checked](https://github.com/exercism/v3/blob/master/languages/rust/README.md).

This is *looooow* priority :smile:

**Comment by BethanyG** [comment]
Going to tag onto this rather than open a separate issue ....because there are many many more things that are more important!  😄 

The same is true for the Python track.  We've just updated https://github.com/exercism/v3/tree/master/languages/python, but that's not reflected in the info on https://tracks.exercism.io/python.

**Comment by SleeplessByte** [comment]
It's reflected. Click the ❌ . It's very clear on _why_ it's an X.

![image](https://user-images.githubusercontent.com/1964376/83316985-cc1c7f80-a229-11ea-8b2b-71d6efe4a22b.png)

**Comment by BethanyG** [comment]
[Python] Totally get that for our concept exercises  😄   Buuuuut -  
-  "Have a kick off discussion" and 
-  "Add GitHub issues for 20 concept exercises (ok, ok - it is officially 19 atm, but we closed one as completed....)

Are indeed both complete, but not noted.  I'll take care of the TODO in the concept file as well.  😄

**Comment by SleeplessByte** [comment]
Have a kick off discussion could not be automated, so there is no ✔️  and not ❌.

🙉 ❤️

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom for the items that don't have a check, perhaps we add a ➖ or ❔ ?

Sounds like a good idea!

**Comment by ErikSchierboom** [comment]
I'm wondering if we should keep the "Have a kick-off discussion between track maintainers" item, as we have no way of checking it.

**Comment by ErikSchierboom** [comment]
I've [created a PR to dynamically check the status of 20 Concept Exercise issues](https://github.com/exercism/v3-dashboard/pull/36) item.

**Comment by SleeplessByte** [comment]
PR was merged and deployed!

**Comment by iHiD** [comment]
I don't mind not being able to verify it, but it is rather variable in terms of if all the maintainers change its a useless tickbox. So maybe remove it now we're further in?

**Comment by ErikSchierboom** [comment]
Yep, that would also be my suggestion. Let me do that.
