### ISSUE TITLE
Wizard [Idea]: Pull Relevant Sections from Concept Exercise Issue  into Design Section

### ISSUE THREAD

**Issue by BethanyG** [exercism/v3-dashboard#29]
Fully understand if this is not practical or do-able.  

In looking at https://github.com/exercism/v3/issues/1384 for Python & the wizard for creating an exercise, multiple sections can be cut-and-pasted from one to the other.  Would it be possible to do this automatically?  Seems a shame to do the work to log an issue only to re-do that work when making a concept exercise.

**Comment by ErikSchierboom** [comment]
Closed by #46
