### ISSUE TITLE
Add progress indicators when creating new exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-dashboard#31]
Currently, the text changes when creating a new exercise on the background, but we could do with a bit more visual feedback (e.g. a spinner or something like that).

**Comment by neenjaw** [comment]
I would be interested in this if you are still looking for help with it

**Comment by ErikSchierboom** [comment]
Absolutely! I'll assign it to you.

**Comment by ErikSchierboom** [comment]
I think there's a `LoadingIndicator` class somewhere in the source code already that could be useful.

**Comment by ErikSchierboom** [comment]
Closed by #63
