### ISSUE TITLE
Show message when no new or improve exercise issues are found

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-dashboard#49]
The contributing page lists open issues for creating or improving concept exercises. When none can be found, a nice message should be displayed notifying the user of this fact.

**Comment by JesseSingleton** [comment]
@ErikSchierboom I'd like to take this!

**Comment by ErikSchierboom** [comment]
Sure! I've assigned it to you.

**Comment by ErikSchierboom** [comment]
Closed by #54
