### ISSUE TITLE
[Suggestion] Human readable branch names

### ISSUE THREAD

**Issue by neenjaw** [exercism/v3-dashboard#52]
Just used the dashboard to try it out making a new PR.

A good experience to the PR portion.  Concern is from that point on it is (right now) continued on github.  And while much can be accomplished in the web-browser it probably still relies on checking out branches locally.  The random branch name is very hard to work with/read.  What if it was more along the lines of how docker names their image instances:

see: https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go

So it could generate a name like:

`<track>-<concept>-<random adj>-<random-noun>` e.g. `elixir-metaprogramming-elated-wozniak`

Thoughts?

**Comment by ErikSchierboom** [comment]
> The random branch name is very hard to work with/read.

Yep, this is definitely not ideal. 

> So it could generate a name like:
>
> `<track>-<concept>-<random adj>-<random-noun>`

My main problem here is choosing the adjectives and nouns to be used such that we can guarantee that it does not create any weird or offensive combination. What if we would just do: `<track>-<concept>-<number>`, where `number` would be the first number (starting from 1) for which there isn't already an existing branch?

**Comment by neenjaw** [comment]
Sure

**Comment by ErikSchierboom** [comment]
Cool! I'll work on this tomorrow probably :)

**Comment by ErikSchierboom** [comment]
PR submitted: https://github.com/exercism/website/pull/953
