### ISSUE TITLE
New Exercise Issue should specify exercise name

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3-dashboard#57]
It might be worth modifying the _New Exercise_ issue template to specify an exercise name and propagate that to the _New Exercise_ page.  Maintainers are in a better position to concoct a name than a contributor who may not have a feel for the conventions in use.  I appreciate that there is a steer towards documentation but it's still a big ask for a newbie contributor who just wants to get on with the example code.

**Comment by ErikSchierboom** [comment]
So using the concept as the name of the exercise, pre-filling it. This makes sense!

**Comment by mikedamay** [comment]
sounds good
