### ISSUE TITLE
Markdown docs not pretty enough in PR.

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3-dashboard#58]
Created PR 1651 from v3 dashboard and the format checks faild for _design.md_ and _instructions.md_

**Comment by ErikSchierboom** [comment]
I've just checked, and there were three Markdown issues:

1. There was an unneeded space in the instructions
1. There was a missing final empty line in the instructions
1. There was an additional space in the last prerequisite (this was a mistake already in the [original issue](https://github.com/exercism/v3/issues/1642)).

It would be nice if we could automatically fix this. Maybe we should automatically post a comment with the `/format` command for these new exercises? @iHiD any thoughts?

**Comment by mikedamay** [comment]
My experience previously has been that adding `/format` to the create command has no effect but that may be my inexperience.  I actually tried closing and reopening #1651 with `/format` but even that didn't fix it.

**Comment by ErikSchierboom** [comment]
I think we have an open issue with `/format` not working that @SaschaMann is working on.

**Comment by SaschaMann** [comment]
It's fixed now.

> Maybe we should automatically post a comment with the /format command for these new exercises? @iHiD any thoughts?

Might be nicer to trigger it with a repository dispatch event directly, if the dashboard setup allows it

**Comment by ErikSchierboom** [comment]
I don't think it does, but I can check.

**Comment by iHiD** [comment]
> I don't think it does, but I can check.

We could have an endpoint that triggers it.

**Comment by ErikSchierboom** [comment]
> Might be nicer to trigger it with a repository dispatch event directly, if the dashboard setup allows it

I don't think we _can_ do this, as we're not actually creating the pull requests ourselves, but are letting the user do that themselves.

**Comment by ErikSchierboom** [comment]
We'd have to tweak things a bit (which we _can_ do of course). Maybe it is a good idea to automatically create the PR anyways instead of having the student create the PR themselves. I'm not sure.

**Comment by mikedamay** [comment]
If we create the PR then I imagine we can ensure it is a DRAFT if that's what we want and I suspect we may not be able to set in advance.

**Comment by SaschaMann** [comment]
That sounds more complicated than it needs to be just for formatting. Another nicer option than actually posting the comment could be a trigger so that format runs automatically on PRs whose branches match the dashboard branch scheme?

**Comment by ErikSchierboom** [comment]
> Another nicer option than actually posting the comment could be a trigger so that format runs automatically on PRs whose branches match the dashboard branch scheme?

That might be a good idea, although new PR's could theoretically also use the same scheme. As long as we do post a comment when we change anything, I think this could work.
