### ISSUE TITLE
Warn Casual User that there are lists of issues available.

### ISSUE THREAD

**Issue by mikedamay** [exercism/v3-dashboard#59]
Perhaps we could have a warning when you click on the _New Exercise_ tab directly to explain that the workflow is to pick up an issue from the _Contributing_ tab.

**Comment by ErikSchierboom** [comment]
I like it!

**Comment by ErikSchierboom** [comment]
@mikedamay This is now live! Thanks for the suggestion.

**Comment by mikedamay** [comment]
Excellent.  I'm not seeing it for C# at https://v3.exercism.io/csharp/new-exercise.  Where should I be looking?

**Comment by ErikSchierboom** [comment]
@mikedamay You only see if it there isn't any data in the form. The rationale behind that being that you only need to be shown the warning once: when starting.

**Comment by mikedamay** [comment]
Sounds good
